vezetéknév = input ('Mi a vezetékneved? ')
keresztnév = input ('Mi a keresztneved? ')
születésiév = input ('Mikor szulettél?')
csillagjegy = input ('Mi a csillag jegyed?')
print('a te neved', vezetéknév, keresztnév, )
print('születési éved',születésiév, 'csillag jegyed' ,csillagjegy ,)
